package com.joinflatshare.constants

/**
 * Created by debopam on 28/11/22
 */
object IntentFilterConstants {
    const val INTENT_FILTER_INTERNET = "INTENT_FILTER_INTERNET"
    const val INTENT_FILTER_CONSTANT_RELOAD_PROFILE_IMAGE = "INTENT_FILTER_CONSTANT_RELOAD_PROFILE_IMAGE"
    const val INTENT_FILTER_CONSTANT_READ_SMS = "INTENT_CONSTANT_READ_SMS"
    const val INTENT_FILTER_CONSTANT_RELOAD_NOTIFICATION = "INTENT_FILTER_CONSTANT_RELOAD_NOTIFICATION"
    const val INTENT_FILTER_CONSTANT_CHAT_COUNT = "INTENT_FILTER_CONSTANT_CHAT_COUNT"
    const val INTENT_FILTER_CONSTANT_FIREBASE_TOKEN_UPDATED = "INTENT_FILTER_CONSTANT_FIREBASE_TOKEN_UPDATED"
    const val INTENT_FILTER_CONSTANT_CONTACTS_LOADED = "INTENT_FILTER_CONSTANT_CONTACTS_LOADED"
    const val INTENT_FILTER_CONSTANT_USER_LOCATION_UPDATED = "INTENT_FILTER_CONSTANT_USER_LOCATION_UPDATED"
}