package com.joinflatshare.constants

object NotificationConstants {
    const val NOTIFICATION_TYPE_GENERAL_FLAT = "NOTIFICATION_TYPE_GENERAL_FLAT"
    const val NOTIFICATION_TYPE_GENERAL_USER = "NOTIFICATION_TYPE_GENERAL_USER"
    const val NOTIFICATION_TYPE_NO_NAVIGATION = "NOTIFICATION_TYPE_NO_NAVIGATION"
    const val NOTIFICATION_TYPE_INVITE_FLAT_MEMBER = "NOTIFICATION_TYPE_INVITE_FLAT_MEMBER"
    const val NOTIFICATION_TYPE_INVITE_FRIEND = "NOTIFICATION_TYPE_INVITE_FRIEND"
    const val NOTIFICATION_TYPE_CONNECTION_F2U = "NOTIFICATION_TYPE_CONNECTION_F2U"
    const val NOTIFICATION_TYPE_CONNECTION_U2F = "NOTIFICATION_TYPE_CONNECTION_U2F"
    const val NOTIFICATION_TYPE_CONNECTION_FHT = "NOTIFICATION_TYPE_CONNECTION_FHT"
    const val NOTIFICATION_TYPE_CHAT_SFS_F2U = "NOTIFICATION_TYPE_CHAT_SFS_F2U"
    const val NOTIFICATION_TYPE_CHAT_FMS_U2F = "NOTIFICATION_TYPE_CHAT_FMS_U2F"
    const val NOTIFICATION_TYPE_CHAT = "NOTIFICATION_TYPE_CHAT"
    const val NOTIFICATION_TYPE_GENERAL_USER_EDIT = "NOTIFICATION_TYPE_GENERAL_USER_EDIT"
    const val NOTIFICATION_TYPE_GENERAL_FLAT_EDIT = "NOTIFICATION_TYPE_GENERAL_FLAT_EDIT"
    const val NOTIFICATION_TYPE_CHAT_FHT_U2U = "NOTIFICATION_TYPE_CHAT_FHT_U2U"
    const val NOTIFICATION_TYPE_SENDBIRD = "NOTIFICATION_TYPE_SENDBIRD"
    const val NOTIFICATION_TYPE_GET_VERIFIED_500="NOTIFICATION_TYPE_GET_VERIFIED_500"
    const val NOTIFICATION_TYPE_GET_VERIFIED_500_PAST_12 = "NOTIFICATION_TYPE_GET_VERIFIED_500_PAST_12"
    const val NOTIFICAITON_TYPE_DATING_CASUAL = "NOTIFICATION_TYPE_CONNECTION_CSU"
    const val NOTIFICATION_TYPE_DATING_CSU_U2U = "NOTIFICATION_TYPE_CHAT_CSU_U2U"
    const val NOTIFICAITON_TYPE_DATING_LONG_TERM = "NOTIFICATION_TYPE_CONNECTION_LTR"
    const val NOTIFICATION_TYPE_DATING_LTR_U2U = "NOTIFICATION_TYPE_CHAT_LTR_U2U"
    const val NOTIFICAITON_TYPE_DATING_ACTIVITY_PARTNERS = "NOTIFICATION_TYPE_CONNECTION_ACT"
    const val NOTIFICATION_TYPE_DATING_ACT_U2U = "NOTIFICATION_TYPE_CHAT_ACT_U2U"

    var generalNotificationCount = 0
    var friendRequestCount = 0
    var flatInvitationCount = 0
    var chatRequestCount = 0
}